apiVersion: v1
kind: Service
metadata: 
  name: myapp-svc
spec:
  type: ClusterIP
  ports:
  -  port: 8080
     targetPort: 80
  selector:
    role: myapp


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-pod
spec:
  replicas: 2
  selector:
    matchLabels:
        role: myapp
  template:
    metadata:
      labels:
        role: myapp
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
